[package]
name = "si5351"
version = "0.1.1"
categories = ["embedded-hal-driver", "ham-radio", "clock", "pll" ]
authors = ["Ilya Epifanov <elijah.epifanov@gmail.com>"]

[dependencies]
embedded-hal = "0.1"
bitflags = "1.0"
